import Recommendations from "../components/Recommendations";

export default function Dashboard({ customer }) {
  const username = customer?.username || "Touqeer";

  return (
    <div className="min-h-screen bg-[#f7f7f5]">

      {/* Hero */}
      <section className="store-container pt-12 pb-8">
        <div className="max-w-3xl">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-neutral-400">
            Personalized for you
          </p>

          <h1 className="mt-3 text-4xl font-semibold tracking-[-0.03em] text-neutral-950 sm:text-5xl">
            Good afternoon, {username}.
          </h1>

          <p className="mt-4 max-w-2xl text-base leading-7 text-neutral-500">
            Discover products selected by VectorLoom using your preferences,
            product characteristics, and recommendation signals.
          </p>
        </div>
      </section>

      {/* Recommendation Engine */}
      <section className="store-container pb-12">
        <div className="mb-6 flex items-end justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">
              VectorLoom Intelligence
            </p>

            <h2 className="mt-2 text-2xl font-semibold tracking-tight text-neutral-950">
              Recommended for you
            </h2>

            <p className="mt-1 text-sm text-neutral-500">
              Personalized recommendations generated by our hybrid engine.
            </p>
          </div>
        </div>

        <Recommendations customer={customer} />
      </section>

      {/* Explanation */}
      <section className="border-t border-neutral-200 bg-white">
        <div className="store-container py-12">

          <div className="max-w-2xl">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-400">
              How VectorLoom works
            </p>

            <h2 className="mt-2 text-2xl font-semibold tracking-tight text-neutral-950">
              Recommendations built around you.
            </h2>

            <p className="mt-3 text-sm leading-6 text-neutral-500">
              VectorLoom combines multiple recommendation signals to rank
              products that are most relevant to the customer.
            </p>
          </div>

          <div className="mt-8 grid grid-cols-1 gap-4 md:grid-cols-3">

            <div className="rounded-2xl border border-neutral-200 bg-[#fafafa] p-6">
              <p className="text-xs font-semibold uppercase tracking-wider text-neutral-400">
                01
              </p>

              <h3 className="mt-4 text-base font-semibold text-neutral-900">
                Customer Behavior
              </h3>

              <p className="mt-2 text-sm leading-6 text-neutral-500">
                Collaborative signals identify patterns between customers
                and products.
              </p>
            </div>

            <div className="rounded-2xl border border-neutral-200 bg-[#fafafa] p-6">
              <p className="text-xs font-semibold uppercase tracking-wider text-neutral-400">
                02
              </p>

              <h3 className="mt-4 text-base font-semibold text-neutral-900">
                Product Similarity
              </h3>

              <p className="mt-2 text-sm leading-6 text-neutral-500">
                Product attributes such as type, colour, department and
                description contribute to content-based recommendations.
              </p>
            </div>

            <div className="rounded-2xl border border-neutral-200 bg-[#fafafa] p-6">
              <p className="text-xs font-semibold uppercase tracking-wider text-neutral-400">
                03
              </p>

              <h3 className="mt-4 text-base font-semibold text-neutral-900">
                Hybrid Ranking
              </h3>

              <p className="mt-2 text-sm leading-6 text-neutral-500">
                VectorLoom combines recommendation signals and returns the
                highest-ranked products for the customer.
              </p>
            </div>

          </div>
        </div>
      </section>

    </div>
  );
}